### ISSUE TITLE
Should we use `juliaup-channel` (or just `channel`) instead of `julia-version`?

### ISSUE THREAD

**Issue by davidanthoff** [julia-actions/install-juliaup#59]
The language in Juliaup world is pretty consistent, i.e. that we call that "channel"...

**Comment by DilumAluthge** [comment]
Yeah, it would be good to keep things in this action consistent with the rest of the Juliaup world.

I'd be fine with renaming `julia-version` to `juliaup-channel` or `channel`.

**Comment by DilumAluthge** [comment]
@davidanthoff What do you prefer between `channel` and `juliaup-channel`?
